#!/usr/bin/env ruby
require 'moneymanager'
require 'commander/import'

program :name, 'mm'
program :version, Moneymanager::VERSION
program :description, 'Manage your money via commandline'

command :add do |c|
  c.syntax = 'mm add <path>'
  c.description = 'Import the CSV file'
  c.action do |args, _options|
    abort(c.syntax) if args.first.nil?
    parser = Moneymanager::Parser.new args.first
    entries = parser.parse
    archiver = Moneymanager::Archiver.new
    archiver.store(entries)
  end
end

command :reset do |c|
  c.syntax = 'mm reset'
  c.description = 'Delete the current archive (danger zone!)'
  c.action do |_args, _options|
    if agree('Do you really want to delete everything?')
      Moneymanager::Archiver.reset
    end
  end
end

command :print do |c|
  c.syntax = 'mm print [--month <month>]'
  c.description = 'Print the list of transactions'
  c.option '--month INTEGER', Integer, 'Specify the month to print.'
  c.action do |_args, options|
    entries = get_entries(options.month)
    Layout.print_multiple(entries)
  end
end

command :tag do |c|
  c.syntax = 'mm tags'
  c.description = 'Print the list of transactions'
  c.option '--month INTEGER', Integer, 'Specify the month to tag.'
  c.action do |_args, options|
    entries = get_entries(options.month)
    Tagger.new.retag(entries)
  end
end

command :review do |c|
  c.syntax = 'mm review'
  c.description = 'Start the review process'
  c.option '--month INTEGER', Integer, 'Specify the month to review.'
  c.action do |_args, options|
    entries = get_entries(options.month)
    Reviewer.new.review(entries)
  end
end

command :report do |c|
  c.syntax = 'mm report'
  c.description = 'Print all the revenues and all the expenses grouped by tag'
  c.option '--month INTEGER', Integer, 'Specify the month to report.'
  c.action do |_args, options|
    entries = get_entries(options.month)

    prompt = TTY::Prompt.new
    command = prompt.select('Which type of report?') do |menu|
      menu.choice 'Total (Incomes)', :global_incomes
      menu.choice 'Total (Expenses)', :global_expenses
      menu.choice 'All Incomes', :all_incomes
      menu.choice 'All Expenses', :all_expenses
      menu.choice 'Specific Tag', :one_tag
    end
    report = Report.new
    case command
    when :global_incomes
      report.print_total_report(entries, true)
    when :global_expenses
      report.print_total_report(entries, false)
    when :all_incomes
      report.print_group_by_categories_report(entries, true)
    when :all_expenses
      report.print_group_by_categories_report(entries, false)
    when :one_tag
      archiver = Moneymanager::Archiver.new
      tags = archiver.tags.sort!
      tag = prompt.select('Select a tag.', tags, per_page: 30)
      report.print_group_by_month_report(entries,tag)
      end
  end
end



def get_entries(month)
  archiver = Moneymanager::Archiver.new
  if month.nil?
    archiver.all_entries
  else
    archiver.all_entries_per_month(month)
  end
end
